# Generated by Django 3.0.8 on 2020-10-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='professors',
            field=models.ManyToManyField(to='accounts.Courses'),
        ),
    ]
