# Generated by Django 3.0.8 on 2020-10-13 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201013_1912'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
        migrations.RenameModel(
            old_name='Professors',
            new_name='Professor',
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
