# Generated by Django 3.0.8 on 2020-11-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201115_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='id_number',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_number',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
